# Generated by Django 3.1.6 on 2022-04-20 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0006_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='users',
            new_name='user',
        ),
    ]
